// const typeToIcon = {
//     'Sacred & Religious Sites'
//     'Game & Entertainment Centers'
//     'Monuments & Statues'
//     'Architectural Buildings'
//     'Castles'
//     'Ancient Ruins'
//     'Specialty Museums'
//     'Gift & Specialty Shops'
//     'Points of Interest & Landmarks'
//     'Historic Walking Areas'
//     'Scenic Walking Areas'
//     'Hammams & Turkish Baths'
//     'Spas'
//     'Bars & Clubs'
//     'History Museums'
//     'Art Museums'
//     'Concerts'
//     'Karaoke Bars'
//     'Bowling Alleys'
// }
